### ISSUE TITLE
Flask 3 incompatible with scaffold

### ISSUE THREAD

**Issue by davidwtbuxton** [google/gae-secure-scaffold-python3#21]

**Comment by davidwtbuxton** [comment]
Error:

```
(.venv) $ python -m flask --app main run
Usage: python -m flask run [OPTIONS]
Try 'python -m flask run --help' for help.

Error: While importing 'main', an ImportError was raised:

Traceback (most recent call last):
  File "/demo/.venv/lib/python3.11/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/demo/main.py", line 1, in <module>
    import securescaffold
  File "/demo/.venv/lib/python3.11/site-packages/securescaffold/__init__.py", line 16, in <module>
    from .factory import AppConfig, create_app
  File "/demo/.venv/lib/python3.11/site-packages/securescaffold/factory.py", line 21, in <module>
    import flask_seasurf
  File "/demo/.venv/lib/python3.11/site-packages/flask_seasurf.py", line 28, in <module>
    from flask import (_app_ctx_stack, current_app, g, has_request_context, request,
ImportError: cannot import name '_app_ctx_stack' from 'flask' (/demo/.venv/lib/python3.11/site-packages/flask/__init__.py)
```
